Repository wecode-bootcamp-korea/29-westagram-backend-3-team, pull requests merged in 2022-01, with the labels that each got.

#3 [모휘정] Mission 2: 모델링
  students/hwijeong/westagram/users/__init__.py
  students/hwijeong/westagram/users/admin.py
  students/hwijeong/westagram/users/apps.py
  students/hwijeong/westagram/users/migrations/0001_initial.py
  students/hwijeong/westagram/users/migrations/__init__.py
  students/hwijeong/westagram/users/models.py
  students/hwijeong/westagram/users/tests.py
  students/hwijeong/westagram/users/views.py
  students/hwijeong/westagram/westagram/settings.py
Labels: 멘토 리뷰 요청

#6 [동훈] Misson 2 : 모델링
  students/donghun/users/__init__.py
  students/donghun/users/admin.py
  students/donghun/users/apps.py
  students/donghun/users/migrations/__init__.py
  students/donghun/users/models.py
  students/donghun/users/tests.py
  students/donghun/users/views.py
  students/donghun/westagram/settings.py
Labels: 멘토 리뷰 요청

#7 [ 이강일 ] Mission : 3 회원가입 기능 구현
  students/kangil/westagram/users/migrations/0001_initial.py
  students/kangil/westagram/users/migrations/0002_rename_contact_number_user_phone_number.py
  students/kangil/westagram/users/models.py
  students/kangil/westagram/users/urls.py
  students/kangil/westagram/users/views.py
  students/kangil/westagram/westagram/settings.py
  students/kangil/westagram/westagram/urls.py
Labels: 멘토 리뷰 요청

#8 [모휘정] Mission 3: 회원가입 기능 구현
  students/hwijeong/westagram/users/migrations/0001_initial.py
  students/hwijeong/westagram/users/models.py
  students/hwijeong/westagram/users/urls.py
  students/hwijeong/westagram/users/validators.py
  students/hwijeong/westagram/users/views.py
  students/hwijeong/westagram/westagram/urls.py
Labels: 멘토 리뷰 요청

#10 [ 이강일 ] Mission : 4 로그인 기능 구현
  students/kangil/westagram/users/urls.py
  students/kangil/westagram/users/views.py
Labels: 피어 리뷰 완료, 피어 리뷰 요청

#12 [이동훈] Mission 3: 회원가입 기능 구현
  students/donghun/users/migrations/0001_initial.py
  students/donghun/users/migrations/0002_alter_user_contact.py
  students/donghun/users/migrations/0003_alter_user_contact.py
  students/donghun/users/models.py
  students/donghun/users/urls.py
  students/donghun/users/views.py
  students/donghun/westagram/settings.py
  students/donghun/westagram/urls.py
Labels: 멘토 리뷰 요청

#14 [이동훈] Mission 4: 로그인 기능 구현
  students/donghun/users/urls.py
  students/donghun/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#13 [이강일] Mission : 5 비밀번호 암호화
  students/kangil/westagram/requirements.txt
  students/kangil/westagram/users/urls.py
  students/kangil/westagram/users/views.py
  students/kangil/westagram/westagram/settings.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#16 [이동훈] Misson 5 : 회원가입 비밀번호 암호화 적용
  students/donghun/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료
